name: Main Workflow

on:
  push:
    branches:
      - main
      - actions
    tags:
      - 'v*.*.*'

jobs:
  prep:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Application Version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          change_path: "UrduLanguageTools"
          version_format: "${major}.${minor}.${patch}.${increment}"

  build:
    runs-on: windows-latest
    needs: [prep]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Create Build Directory
        run: mkdir _build

      - name: Restore NuGet Packages
        run: nuget restore UrduLanguageTools.sln

      - name: Import Code Signing Certificate
        shell: pwsh
        run: |
          ./ops/ImportCodeSigningCert.ps1 `
            -CertificateBase64 "${{ secrets.CODE_SIGNING_CERTIFICATE }}" `
            -CertificatePassword "${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}" `
            -CertificateFilePath "UrduLanguageTools/CodeSigningCert.pfx"

      - name: Build Solution
        run: msbuild.exe UrduLanguageTools.sln `
          /p:Platform="Any CPU" `
          /p:Configuration="Release" `
          /p:DeployOnBuild=true `
          /p:WebPublishMethod=FileSystem `
          /p:DeleteExistingFiles=True `
          /p:PublishUrl="../_build" `
          /p:Version="${{ needs.prep.outputs.version || '1.0.0.0' }}" `
          /p:SignManifest=true `
          /p:ManifestCertificateThumbprint="${{ secrets.CODE_SIGNING_CERTIFICATE_THUMBPRINT }}"
        
      - name: Copy Code Signing Certificate
        run: cp UrduLanguageTools/CodeSigningCert.pfx _build

  release:
    runs-on: ubuntu-latest
    needs: [build]
    #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: fregante/release-with-changelog@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release ${{ needs.prep.outputs.version }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: UrduLanguageTools
          path: "./_build"

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./_build/publish/UrduLanguageTools.zip"
          asset_name: UrduLanguageTools.zip
          asset_content_type: application/zip